#!/bin/bash
#/etc/init.d/chat

case "$1" in
    start)
        echo "Starting chat service..."
        /home/yebin/chatroom/.venv/bin/python /home/yebin/chatroom/chat.py > /dev/null 2>&1 &
        ;;
    stop)
        echo "Stopping chat service..."
        killall /home/yebin/chatroom/.venv/bin/python
        ;;
    *)
        echo "Usage: /etc/init.d/chat{start|stop}"
        exit 1
        ;;
esac

exit 0
