#!/bin/bash
#/etc/init.d/myblog

case "$1" in
    start)
        echo "Starting myblog..."
        /home/yebin/myblog/.venv/bin/python /home/yebin/myblog/app.py > /dev/null 2>&1 &
        ;;
    stop)
        echo "Stopping myblog..."
        killall /home/yebin/myblog/.venv/bin/python
        ;;
    *)
        echo "Usage: /etc/init.d/myblog{start|stop}"
        exit 1
        ;;
esac

exit 0
